apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mooncake-operator-ui-role
  labels:
    app.kubernetes.io/name: mooncake-operator-ui
    app.kubernetes.io/component: webui
rules:
- apiGroups:
  - mooncake.io
  resources:
  - mooncakeclusters
  verbs:
  - get
  - list
  - watch
  - create
  - delete
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - get
  - list
  - watch
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
