apiVersion: v1
kind: ConfigMap
metadata:
  name: mooncake-operator-ui-credentials
  namespace: mooncake-operator-system
  labels:
    app.kubernetes.io/name: mooncake-operator-ui
    app.kubernetes.io/component: webui
data:
  username: admin
  password: admin123
