apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mooncake-operator-system

resources:
- service-account.yaml
- cluster-role.yaml
- cluster-role-binding.yaml
- configmap.yaml
- deployment.yaml
- service.yaml

images:
- name: mooncake-operator-ui
  newName: mooncake-operator-ui
  newTag: latest
