apiVersion: v1
kind: ServiceAccount
metadata:
  name: mooncake-operator-ui
  namespace: mooncake-operator-system
  labels:
    app.kubernetes.io/name: mooncake-operator-ui
    app.kubernetes.io/component: webui
