// Copyright 2024 KVCache.AI
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Maintainer tool: regenerates the committed `dlopen` bindings from
//! `store_c.h`. Run after the C ABI changes:
//!
//! ```bash
//! cargo run --example generate_dlopen_bindings
//! ```
//!
//! The header is taken from `MOONCAKE_STORE_INCLUDE_DIR` (default `../include`).
//! CI should run this and `git diff --exit-code` to catch drift.

use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let include_dir = std::env::var("MOONCAKE_STORE_INCLUDE_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|_| manifest_dir.join("../include"));
    let header = include_dir.join("store_c.h");
    let out = manifest_dir.join("src/generated/ffi_dlopen_bindings.rs");

    let bindings = bindgen::Builder::default()
        .header(header.to_string_lossy())
        .allowlist_function("mooncake_store_.*")
        .allowlist_type("mooncake_.*")
        .dynamic_library_name("MooncakeStoreLib")
        .dynamic_link_require_all(true)
        .raw_line("// @generated by `cargo run --example generate_dlopen_bindings` from store_c.h.")
        .raw_line("// Do not edit by hand; see mooncake-store/rust/README.md to regenerate.")
        .generate()
        .expect("failed to generate dlopen bindings from store_c.h");

    bindings
        .write_to_file(&out)
        .unwrap_or_else(|e| panic!("failed to write {}: {e}", out.display()));
    println!("wrote {}", out.display());
}
