FROM node:20-alpine AS runner
WORKDIR /app

RUN addgroup --system --gid 1001 nodejs && adduser --system --uid 1001 nextjs

COPY server.js ./server.js
COPY lib ./lib
COPY node_modules ./node_modules
COPY .next ./.next
COPY public ./public
COPY package.json ./package.json

USER nextjs
EXPOSE 3000
ENV PORT=3000
CMD ["node", "server.js"]
