apiVersion: v1
kind: ConfigMap
metadata:
  name: mooncake-master-config
data:
  master.yaml: |
    rpc_port: 50051
    rpc_thread_num: 4
    rpc_address: "0.0.0.0"
    rpc_conn_timeout_seconds: 0
    rpc_enable_tcp_no_delay: true

    enable_metric_reporting: true
    metrics_port: 9003

    enable_http_metadata_server: true
    http_metadata_server_host: "0.0.0.0"
    http_metadata_server_port: 8080

    default_kv_lease_ttl: 5000
    default_kv_soft_pin_ttl: 1800000
    allow_evict_soft_pinned_objects: true
    eviction_ratio: 0.05
    eviction_high_watermark_ratio: 0.95

    memory_allocator: "offset"
    allocation_strategy: "random"

    enable_snapshot: true
    enable_snapshot_restore: true
    snapshot_interval_seconds: 60
    snapshot_retention_count: 3
    snapshot_object_store_type: "local"
