// Copyright 2026 KVCache.AI
#include "tent/transport/tcp/high_performance_tcp_buffer_registry.h"
#include <limits>
namespace mooncake::tent {
HighPerformanceTcpBufferRegistry::Lease::Lease(std::shared_ptr<Entry> e):entry_(std::move(e)){}
HighPerformanceTcpBufferRegistry::Lease& HighPerformanceTcpBufferRegistry::Lease::operator=(Lease&& o) noexcept { if(this!=&o){reset();entry_=std::move(o.entry_);}return *this; }
void HighPerformanceTcpBufferRegistry::Lease::reset(){if(!entry_)return; entry_->active_leases.fetch_sub(1,std::memory_order_release); entry_->drained.notify_all(); entry_.reset();}
HighPerformanceTcpBufferRegistry::Lease::~Lease(){reset();}
void* HighPerformanceTcpBufferRegistry::Lease::data() const{return entry_?reinterpret_cast<void*>(entry_->base):nullptr;}
uint64_t HighPerformanceTcpBufferRegistry::Lease::length() const{return entry_?entry_->length:0;}
Status HighPerformanceTcpBufferRegistry::add(uint64_t base,uint64_t length,Permission p,uint64_t* id){if(!length||base>std::numeric_limits<uint64_t>::max()-length)return Status::InvalidArgument("Invalid hp TCP buffer range" LOC_MARK);std::lock_guard<std::mutex>g(mutex_);auto next=entries_.upper_bound(base);if(next!=entries_.end()&&base+length>next->second->base)return Status::InvalidArgument("Overlapping hp TCP buffer" LOC_MARK);if(next!=entries_.begin()){auto prev=std::prev(next);if(prev->second->base+prev->second->length>base)return Status::InvalidArgument("Overlapping hp TCP buffer" LOC_MARK);} auto e=std::make_shared<Entry>();e->base=base;e->length=length;e->permission=p;e->registration_id=next_registration_id_++;if(!e->registration_id)e->registration_id=next_registration_id_++;entries_[base]=e;if(id)*id=e->registration_id;return Status::OK();}
Status HighPerformanceTcpBufferRegistry::remove(uint64_t base,uint64_t length){std::unique_lock<std::mutex>g(mutex_);auto it=entries_.find(base);if(it==entries_.end()||it->second->length!=length)return Status::AddressNotRegistered("HP TCP buffer not registered" LOC_MARK);auto e=it->second;e->closing.store(true,std::memory_order_release);entries_.erase(it);e->drained.wait(g,[&]{return e->active_leases.load(std::memory_order_acquire)==0;});return Status::OK();}
Status HighPerformanceTcpBufferRegistry::acquire(uint64_t addr,uint64_t len,uint64_t id,HighPerformanceTcpOpcode op,bool remote,Lease* lease){if(!lease||!len||addr>std::numeric_limits<uint64_t>::max()-len)return Status::InvalidArgument("Invalid hp TCP lease range" LOC_MARK);std::lock_guard<std::mutex>g(mutex_);auto it=entries_.upper_bound(addr);if(it==entries_.begin())return Status::AddressNotRegistered("HP TCP range not registered" LOC_MARK);auto e=std::prev(it)->second;if(e->closing.load(std::memory_order_acquire)||addr<e->base||addr+len>e->base+e->length)return Status::AddressNotRegistered("HP TCP range not registered" LOC_MARK);if(remote){if(e->registration_id!=id)return Status::AddressNotRegistered("Stale HP TCP registration" LOC_MARK);if(e->permission==kLocalReadWrite||(op==HighPerformanceTcpOpcode::kWrite&&e->permission!=kGlobalReadWrite))return Status::AddressNotRegistered("HP TCP permission denied" LOC_MARK);}e->active_leases.fetch_add(1,std::memory_order_relaxed);*lease=Lease(e);return Status::OK();}
Status HighPerformanceTcpBufferRegistry::acquireLocalLease(uint64_t a,uint64_t l,Lease* x){return acquire(a,l,0,HighPerformanceTcpOpcode::kRead,false,x);}
Status HighPerformanceTcpBufferRegistry::acquireRemoteLease(uint64_t a,uint64_t l,uint64_t id,HighPerformanceTcpOpcode op,Lease*x){return acquire(a,l,id,op,true,x);}
size_t HighPerformanceTcpBufferRegistry::size()const{std::lock_guard<std::mutex>g(mutex_);return entries_.size();}
}  // namespace mooncake::tent
