// Copyright 2026 KVCache.AI
#include "tent/transport/tcp/high_performance_tcp_server.h"
#include "tent/transport/tcp/high_performance_tcp_protocol.h"
#include <algorithm>
namespace mooncake::tent { namespace { HighPerformanceTcpStatus ToWire(const Status&s){if(s.ok())return HighPerformanceTcpStatus::kOk;if(s.IsAddressNotRegistered())return HighPerformanceTcpStatus::kRangeRejected;return HighPerformanceTcpStatus::kInternalError;} }
HighPerformanceTcpServer::HighPerformanceTcpServer(Config c,HighPerformanceTcpBufferRegistry*r):config_(std::move(c)),registry_(r){}
HighPerformanceTcpServer::~HighPerformanceTcpServer(){stop();}
Status HighPerformanceTcpServer::start(uint16_t* port){if(!registry_||!port||!config_.chunk_size||!config_.max_transfer_bytes)return Status::InvalidArgument("Invalid HP TCP server configuration" LOC_MARK);try{asio::ip::tcp::endpoint ep;if(config_.bind_address.empty())ep=asio::ip::tcp::endpoint(asio::ip::tcp::v4(),config_.port);else ep=asio::ip::tcp::endpoint(asio::ip::make_address(config_.bind_address),config_.port);acceptor_=std::make_unique<asio::ip::tcp::acceptor>(io_,ep);*port=acceptor_->local_endpoint().port();stopping_=false;accept_thread_=std::thread([this]{acceptLoop();});return Status::OK();}catch(const std::exception&e){return Status::InternalError(std::string("HP TCP listen failed: ")+e.what()+LOC_MARK);}}
Status HighPerformanceTcpServer::stop(){if(stopping_.exchange(true))return Status::OK();if(acceptor_){std::error_code ec;acceptor_->close(ec);}if(accept_thread_.joinable())accept_thread_.join();std::lock_guard<std::mutex>g(session_mutex_);for(auto&t:sessions_)if(t.joinable())t.join();sessions_.clear();return Status::OK();}
void HighPerformanceTcpServer::acceptLoop(){while(!stopping_){try{asio::ip::tcp::socket s(io_);acceptor_->accept(s);s.set_option(asio::ip::tcp::no_delay(true));std::lock_guard<std::mutex>g(session_mutex_);sessions_.emplace_back([this,s=std::move(s)]()mutable{serve(std::move(s));});}catch(const std::exception&){if(!stopping_)continue;return;}}}
void HighPerformanceTcpServer::serve(asio::ip::tcp::socket socket){std::vector<uint8_t> chunk(config_.chunk_size);for(;;){std::array<uint8_t,kHighPerformanceTcpRequestSize> raw{};std::error_code ec;asio::read(socket,asio::buffer(raw),ec);if(ec)return;HighPerformanceTcpRequestFrame f;auto parsed=DecodeHighPerformanceTcpRequest(raw.data(),raw.size(),&f);HighPerformanceTcpResponseFrame rsp{ToWire(parsed),f.request_id,0};if(!parsed.ok()||f.length>config_.max_transfer_bytes){if(parsed.ok())rsp.status=HighPerformanceTcpStatus::kBadLength;asio::write(socket,asio::buffer(EncodeHighPerformanceTcpResponse(rsp)),ec);if(ec)return;continue;}HighPerformanceTcpBufferRegistry::Lease lease;auto st=registry_->acquireRemoteLease(f.remote_addr,f.length,f.registration_id,f.opcode,&lease);if(!st.ok()){rsp.status=ToWire(st);asio::write(socket,asio::buffer(EncodeHighPerformanceTcpResponse(rsp)),ec);if(ec)return;continue;}auto* p=reinterpret_cast<uint8_t*>(lease.data())+(f.remote_addr-reinterpret_cast<uint64_t>(lease.data()));if(f.opcode==HighPerformanceTcpOpcode::kRead){rsp.status=HighPerformanceTcpStatus::kOk;rsp.committed_bytes=f.length;asio::write(socket,asio::buffer(EncodeHighPerformanceTcpResponse(rsp)),ec);if(ec)return;for(uint64_t done=0;done<f.length;){auto n=std::min<uint64_t>(chunk.size(),f.length-done);asio::write(socket,asio::buffer(p+done,n),ec);if(ec)return;done+=n;}}else{for(uint64_t done=0;done<f.length;){auto n=std::min<uint64_t>(chunk.size(),f.length-done);asio::read(socket,asio::buffer(p+done,n),ec);if(ec)return;done+=n;}rsp.status=HighPerformanceTcpStatus::kOk;rsp.committed_bytes=f.length;asio::write(socket,asio::buffer(EncodeHighPerformanceTcpResponse(rsp)),ec);if(ec)return;}}}
}  // namespace mooncake::tent
