# CMake generated Testfile for 
# Source directory: /root/Mooncake/mooncake-store/tests
# Build directory: /root/Mooncake/mooncake-transfer-engine/mooncake-store/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(buffer_allocator_test "/root/Mooncake/mooncake-transfer-engine/mooncake-store/tests/buffer_allocator_test")
set_tests_properties(buffer_allocator_test PROPERTIES  _BACKTRACE_TRIPLES "/root/Mooncake/mooncake-store/tests/CMakeLists.txt;14;add_test;/root/Mooncake/mooncake-store/tests/CMakeLists.txt;17;add_store_test;/root/Mooncake/mooncake-store/tests/CMakeLists.txt;0;")
add_test(allocation_strategy_test "/root/Mooncake/mooncake-transfer-engine/mooncake-store/tests/allocation_strategy_test")
set_tests_properties(allocation_strategy_test PROPERTIES  _BACKTRACE_TRIPLES "/root/Mooncake/mooncake-store/tests/CMakeLists.txt;14;add_test;/root/Mooncake/mooncake-store/tests/CMakeLists.txt;18;add_store_test;/root/Mooncake/mooncake-store/tests/CMakeLists.txt;0;")
add_test(eviction_strategy_test "/root/Mooncake/mooncake-transfer-engine/mooncake-store/tests/eviction_strategy_test")
set_tests_properties(eviction_strategy_test PROPERTIES  _BACKTRACE_TRIPLES "/root/Mooncake/mooncake-store/tests/CMakeLists.txt;14;add_test;/root/Mooncake/mooncake-store/tests/CMakeLists.txt;19;add_store_test;/root/Mooncake/mooncake-store/tests/CMakeLists.txt;0;")
add_test(master_service_test "/root/Mooncake/mooncake-transfer-engine/mooncake-store/tests/master_service_test")
set_tests_properties(master_service_test PROPERTIES  _BACKTRACE_TRIPLES "/root/Mooncake/mooncake-store/tests/CMakeLists.txt;14;add_test;/root/Mooncake/mooncake-store/tests/CMakeLists.txt;20;add_store_test;/root/Mooncake/mooncake-store/tests/CMakeLists.txt;0;")
add_test(master_service_ssd_test "/root/Mooncake/mooncake-transfer-engine/mooncake-store/tests/master_service_ssd_test")
set_tests_properties(master_service_ssd_test PROPERTIES  _BACKTRACE_TRIPLES "/root/Mooncake/mooncake-store/tests/CMakeLists.txt;14;add_test;/root/Mooncake/mooncake-store/tests/CMakeLists.txt;21;add_store_test;/root/Mooncake/mooncake-store/tests/CMakeLists.txt;0;")
add_test(client_integration_test "/root/Mooncake/mooncake-transfer-engine/mooncake-store/tests/client_integration_test")
set_tests_properties(client_integration_test PROPERTIES  _BACKTRACE_TRIPLES "/root/Mooncake/mooncake-store/tests/CMakeLists.txt;14;add_test;/root/Mooncake/mooncake-store/tests/CMakeLists.txt;22;add_store_test;/root/Mooncake/mooncake-store/tests/CMakeLists.txt;0;")
add_test(master_metrics_test "/root/Mooncake/mooncake-transfer-engine/mooncake-store/tests/master_metrics_test")
set_tests_properties(master_metrics_test PROPERTIES  _BACKTRACE_TRIPLES "/root/Mooncake/mooncake-store/tests/CMakeLists.txt;14;add_test;/root/Mooncake/mooncake-store/tests/CMakeLists.txt;23;add_store_test;/root/Mooncake/mooncake-store/tests/CMakeLists.txt;0;")
add_test(posix_file_test "/root/Mooncake/mooncake-transfer-engine/mooncake-store/tests/posix_file_test")
set_tests_properties(posix_file_test PROPERTIES  _BACKTRACE_TRIPLES "/root/Mooncake/mooncake-store/tests/CMakeLists.txt;14;add_test;/root/Mooncake/mooncake-store/tests/CMakeLists.txt;24;add_store_test;/root/Mooncake/mooncake-store/tests/CMakeLists.txt;0;")
add_test(thread_pool_test "/root/Mooncake/mooncake-transfer-engine/mooncake-store/tests/thread_pool_test")
set_tests_properties(thread_pool_test PROPERTIES  _BACKTRACE_TRIPLES "/root/Mooncake/mooncake-store/tests/CMakeLists.txt;14;add_test;/root/Mooncake/mooncake-store/tests/CMakeLists.txt;25;add_store_test;/root/Mooncake/mooncake-store/tests/CMakeLists.txt;0;")
add_test(transfer_task_test "/root/Mooncake/mooncake-transfer-engine/mooncake-store/tests/transfer_task_test")
set_tests_properties(transfer_task_test PROPERTIES  _BACKTRACE_TRIPLES "/root/Mooncake/mooncake-store/tests/CMakeLists.txt;14;add_test;/root/Mooncake/mooncake-store/tests/CMakeLists.txt;26;add_store_test;/root/Mooncake/mooncake-store/tests/CMakeLists.txt;0;")
add_test(segment_test "/root/Mooncake/mooncake-transfer-engine/mooncake-store/tests/segment_test")
set_tests_properties(segment_test PROPERTIES  _BACKTRACE_TRIPLES "/root/Mooncake/mooncake-store/tests/CMakeLists.txt;14;add_test;/root/Mooncake/mooncake-store/tests/CMakeLists.txt;27;add_store_test;/root/Mooncake/mooncake-store/tests/CMakeLists.txt;0;")
add_test(offset_allocator_test "/root/Mooncake/mooncake-transfer-engine/mooncake-store/tests/offset_allocator_test")
set_tests_properties(offset_allocator_test PROPERTIES  _BACKTRACE_TRIPLES "/root/Mooncake/mooncake-store/tests/CMakeLists.txt;14;add_test;/root/Mooncake/mooncake-store/tests/CMakeLists.txt;28;add_store_test;/root/Mooncake/mooncake-store/tests/CMakeLists.txt;0;")
add_test(utils_test "/root/Mooncake/mooncake-transfer-engine/mooncake-store/tests/utils_test")
set_tests_properties(utils_test PROPERTIES  _BACKTRACE_TRIPLES "/root/Mooncake/mooncake-store/tests/CMakeLists.txt;14;add_test;/root/Mooncake/mooncake-store/tests/CMakeLists.txt;29;add_store_test;/root/Mooncake/mooncake-store/tests/CMakeLists.txt;0;")
add_test(client_buffer_test "/root/Mooncake/mooncake-transfer-engine/mooncake-store/tests/client_buffer_test")
set_tests_properties(client_buffer_test PROPERTIES  _BACKTRACE_TRIPLES "/root/Mooncake/mooncake-store/tests/CMakeLists.txt;14;add_test;/root/Mooncake/mooncake-store/tests/CMakeLists.txt;30;add_store_test;/root/Mooncake/mooncake-store/tests/CMakeLists.txt;0;")
add_test(pybind_client_test "/root/Mooncake/mooncake-transfer-engine/mooncake-store/tests/pybind_client_test")
set_tests_properties(pybind_client_test PROPERTIES  _BACKTRACE_TRIPLES "/root/Mooncake/mooncake-store/tests/CMakeLists.txt;14;add_test;/root/Mooncake/mooncake-store/tests/CMakeLists.txt;31;add_store_test;/root/Mooncake/mooncake-store/tests/CMakeLists.txt;0;")
add_test(ipv6_client_test "/root/Mooncake/mooncake-transfer-engine/mooncake-store/tests/ipv6_client_test")
set_tests_properties(ipv6_client_test PROPERTIES  _BACKTRACE_TRIPLES "/root/Mooncake/mooncake-store/tests/CMakeLists.txt;14;add_test;/root/Mooncake/mooncake-store/tests/CMakeLists.txt;32;add_store_test;/root/Mooncake/mooncake-store/tests/CMakeLists.txt;0;")
add_test(client_metrics_test "/root/Mooncake/mooncake-transfer-engine/mooncake-store/tests/client_metrics_test")
set_tests_properties(client_metrics_test PROPERTIES  _BACKTRACE_TRIPLES "/root/Mooncake/mooncake-store/tests/CMakeLists.txt;14;add_test;/root/Mooncake/mooncake-store/tests/CMakeLists.txt;33;add_store_test;/root/Mooncake/mooncake-store/tests/CMakeLists.txt;0;")
add_test(serializer_test "/root/Mooncake/mooncake-transfer-engine/mooncake-store/tests/serializer_test")
set_tests_properties(serializer_test PROPERTIES  _BACKTRACE_TRIPLES "/root/Mooncake/mooncake-store/tests/CMakeLists.txt;14;add_test;/root/Mooncake/mooncake-store/tests/CMakeLists.txt;34;add_store_test;/root/Mooncake/mooncake-store/tests/CMakeLists.txt;0;")
add_test(non_ha_reconnect_test "/root/Mooncake/mooncake-transfer-engine/mooncake-store/tests/non_ha_reconnect_test")
set_tests_properties(non_ha_reconnect_test PROPERTIES  _BACKTRACE_TRIPLES "/root/Mooncake/mooncake-store/tests/CMakeLists.txt;14;add_test;/root/Mooncake/mooncake-store/tests/CMakeLists.txt;35;add_store_test;/root/Mooncake/mooncake-store/tests/CMakeLists.txt;0;")
add_test(storage_backend_test "/root/Mooncake/mooncake-transfer-engine/mooncake-store/tests/storage_backend_test")
set_tests_properties(storage_backend_test PROPERTIES  _BACKTRACE_TRIPLES "/root/Mooncake/mooncake-store/tests/CMakeLists.txt;14;add_test;/root/Mooncake/mooncake-store/tests/CMakeLists.txt;36;add_store_test;/root/Mooncake/mooncake-store/tests/CMakeLists.txt;0;")
add_test(mutex_test "/root/Mooncake/mooncake-transfer-engine/mooncake-store/tests/mutex_test")
set_tests_properties(mutex_test PROPERTIES  _BACKTRACE_TRIPLES "/root/Mooncake/mooncake-store/tests/CMakeLists.txt;14;add_test;/root/Mooncake/mooncake-store/tests/CMakeLists.txt;37;add_store_test;/root/Mooncake/mooncake-store/tests/CMakeLists.txt;0;")
add_test(file_storage_test "/root/Mooncake/mooncake-transfer-engine/mooncake-store/tests/file_storage_test")
set_tests_properties(file_storage_test PROPERTIES  _BACKTRACE_TRIPLES "/root/Mooncake/mooncake-store/tests/CMakeLists.txt;14;add_test;/root/Mooncake/mooncake-store/tests/CMakeLists.txt;38;add_store_test;/root/Mooncake/mooncake-store/tests/CMakeLists.txt;0;")
add_test(task_manager_test "/root/Mooncake/mooncake-transfer-engine/mooncake-store/tests/task_manager_test")
set_tests_properties(task_manager_test PROPERTIES  _BACKTRACE_TRIPLES "/root/Mooncake/mooncake-store/tests/CMakeLists.txt;14;add_test;/root/Mooncake/mooncake-store/tests/CMakeLists.txt;39;add_store_test;/root/Mooncake/mooncake-store/tests/CMakeLists.txt;0;")
subdirs("e2e")
