apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mooncake
resources:
  - ../mooncake-master-deployment
  - servicemonitor.yaml

labels:
  - pairs:
      app.kubernetes.io/name: mooncake-master
      app.kubernetes.io/component: master
      app.kubernetes.io/part-of: mooncake
    includeTemplates: true
    includeSelectors: true