/* Code generated by cmd/cgo; DO NOT EDIT. */

#ifndef LIBK8S_LEASE_WRAPPER_H
#define LIBK8S_LEASE_WRAPPER_H

#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Callback type for holder change notifications */
typedef void (*holder_change_cb_t)(void* ctx,
                                    const char* holder, size_t holderSize,
                                    int64_t leaseTransitions);

/* Initialize the K8s client. Must be called before any other function. */
extern int K8sLeaseInit(char** errMsg);

/* Start a leader election for the given namespace/lease name. */
extern int K8sLeaseRunElection(char* ns, char* leaseName, char* identity,
                                int leaseDurationSec, int renewDeadlineSec,
                                int retryPeriodSec, char** errMsg);

/* Wait for the election to be won. Returns 0 on success, -1 on timeout/error. */
extern int K8sLeaseWaitElected(char* ns, char* leaseName, int timeoutSec,
                                long long* leaseTransitions, char** errMsg);

/* Wait for the election to be lost (leader lease lost). */
extern int K8sLeaseWaitLost(char* ns, char* leaseName, char** errMsg);

/* Cancel a running election. */
extern int K8sLeaseCancelElection(char* ns, char* leaseName, char** errMsg);

/* Get the current holder of a lease.
 * Returns 0 with holder set, 1 if lease not found, -1 on error. */
extern int K8sLeaseGetHolder(char* ns, char* leaseName, char** holderIdentity,
                              long long* leaseTransitions, char** errMsg);

/* Watch for holder changes on a lease. The callback is invoked on each change. */
extern int K8sLeaseWatchHolder(char* ns, char* leaseName,
                                void* callbackContext,
                                holder_change_cb_t callbackFunc,
                                char** errMsg);

/* Cancel a running watch. */
extern int K8sLeaseCancelWatch(char* ns, char* leaseName, char** errMsg);

#ifdef __cplusplus
}
#endif

#endif /* LIBK8S_LEASE_WRAPPER_H */
