/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "k8s_lease_wrapper.go"

#include <stdint.h>
#include <stdlib.h>
#include <string.h>

// Trampoline to invoke C/C++ callback safely from Go via cgo.
typedef void (*holder_change_cb_t)(void* ctx,
                                    const char* holder, size_t holderSize,
                                    int64_t leaseTransitions);

static inline void call_holder_change_cb(holder_change_cb_t func, void* ctx,
                                          const char* holder, size_t holderSize,
                                          int64_t leaseTransitions) {
  func(ctx, holder, holderSize, leaseTransitions);
}

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern int K8sLeaseInit(char** errMsg);
extern int K8sLeaseRunElection(char* ns, char* leaseName, char* identity, int leaseDurationSec, int renewDeadlineSec, int retryPeriodSec, char** errMsg);
extern int K8sLeaseWaitElected(char* ns, char* leaseName, int timeoutSec, long long int* leaseTransitions, char** errMsg);
extern int K8sLeaseWaitLost(char* ns, char* leaseName, char** errMsg);
extern int K8sLeaseCancelElection(char* ns, char* leaseName, char** errMsg);
extern int K8sLeaseGetHolder(char* ns, char* leaseName, char** holderIdentity, long long int* leaseTransitions, char** errMsg);
extern int K8sLeaseWatchHolder(char* ns, char* leaseName, void* callbackCtx, holder_change_cb_t callbackFunc, char** errMsg);
extern int K8sLeaseCancelWatch(char* ns, char* leaseName, char** errMsg);

#ifdef __cplusplus
}
#endif
