[workspace]
members = [
    "crates/mooncake-transport-sys",
    "crates/mooncake-transport",
    "crates/mooncake-store-core",
    "crates/mooncake-metadata",
    "crates/mooncake-store-client",
    "crates/mooncake-store-e2e",
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"
license = "Apache-2.0"

[workspace.dependencies]
parking_lot = "0.12"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
