"""Framework-neutral KV-cache reshard contracts and planning API."""

from .completion import KVCacheCompletion, KVCacheTargetReceipt, KVCacheWriterReceipt
from .executor import KVCacheTransferEngineExecutor
from .manifest import (
    KVCacheBufferBinding,
    KVCacheComponent,
    KVCacheDescriptor,
    KVCacheLayout,
    KVCachePlacementManifest,
    KVCachePlacementPart,
    KVCacheRank,
    KVCacheRuntimeBinding,
    KVCacheRuntimeBindingManifest,
    KVCacheRuntimeBuffer,
    KVCacheSnapshotDescriptor,
    KVCacheTopology,
    KVCacheTopologyParticipant,
    SnapshotId,
    assemble_kv_cache_placement,
    placement_fragment_id,
    validate_runtime_binding,
    validate_runtime_bindings,
)
from .plan_serde import (
    kv_cache_logical_plan_from_json,
    kv_cache_logical_plan_to_json,
)
from .planner import (
    KVCacheLogicalTransferPlan,
    KVCachePreparedTransferEdge,
    KVCachePreparedTransferPlan,
    KVCacheTransferEdge,
    plan_kv_cache_transfer_to_local_target,
    prepare_kv_cache_transfer,
)
from .resolved import (
    KVCacheRegisteredRegion,
    KVCacheResolvedRange,
    KVCacheResolvedRuntimeBinding,
    KVCacheTransferLimits,
    resolve_contiguous_runtime_binding,
    validate_resolved_runtime_binding,
)
from .runtime_serde import (
    kv_cache_resolved_binding_from_json,
    kv_cache_resolved_binding_to_json,
    kv_cache_runtime_transfer_from_json,
    kv_cache_runtime_transfer_to_json,
    kv_cache_target_receipt_from_json,
    kv_cache_target_receipt_to_json,
    kv_cache_writer_receipt_from_json,
    kv_cache_writer_receipt_to_json,
)
from .serde import (
    kv_cache_part_from_json,
    kv_cache_part_to_json,
    kv_cache_placement_from_json,
    kv_cache_placement_to_json,
    kv_cache_runtime_binding_from_json,
    kv_cache_runtime_binding_to_json,
)
from .snapshot_serde import (
    kv_cache_snapshot_from_json,
    kv_cache_snapshot_to_json,
)
from .transfer import KVCacheRuntimeTransferPlan, KVCacheWrite

__all__ = [
    "KVCacheBufferBinding",
    "KVCacheCompletion",
    "KVCacheComponent",
    "KVCacheDescriptor",
    "KVCacheLayout",
    "KVCacheLogicalTransferPlan",
    "KVCachePlacementManifest",
    "KVCachePlacementPart",
    "KVCachePreparedTransferEdge",
    "KVCachePreparedTransferPlan",
    "KVCacheRank",
    "KVCacheRegisteredRegion",
    "KVCacheResolvedRange",
    "KVCacheResolvedRuntimeBinding",
    "KVCacheRuntimeBinding",
    "KVCacheRuntimeBindingManifest",
    "KVCacheRuntimeBuffer",
    "KVCacheRuntimeTransferPlan",
    "KVCacheSnapshotDescriptor",
    "KVCacheTargetReceipt",
    "KVCacheTopology",
    "KVCacheTopologyParticipant",
    "KVCacheTransferEdge",
    "KVCacheTransferEngineExecutor",
    "KVCacheTransferLimits",
    "KVCacheWrite",
    "KVCacheWriterReceipt",
    "SnapshotId",
    "assemble_kv_cache_placement",
    "kv_cache_logical_plan_from_json",
    "kv_cache_logical_plan_to_json",
    "kv_cache_part_from_json",
    "kv_cache_part_to_json",
    "kv_cache_placement_from_json",
    "kv_cache_placement_to_json",
    "kv_cache_resolved_binding_from_json",
    "kv_cache_resolved_binding_to_json",
    "kv_cache_runtime_binding_from_json",
    "kv_cache_runtime_binding_to_json",
    "kv_cache_runtime_transfer_from_json",
    "kv_cache_runtime_transfer_to_json",
    "kv_cache_snapshot_from_json",
    "kv_cache_snapshot_to_json",
    "kv_cache_target_receipt_from_json",
    "kv_cache_target_receipt_to_json",
    "kv_cache_writer_receipt_from_json",
    "kv_cache_writer_receipt_to_json",
    "placement_fragment_id",
    "plan_kv_cache_transfer_to_local_target",
    "prepare_kv_cache_transfer",
    "resolve_contiguous_runtime_binding",
    "validate_resolved_runtime_binding",
    "validate_runtime_binding",
    "validate_runtime_bindings",
]
