if(CUDAToolkit_FOUND OR USE_SUPA)
  file(GLOB TENT_PLATFORM_CUDA_SOURCES "*.cpp")
  add_library(platform_cuda STATIC ${TENT_PLATFORM_CUDA_SOURCES})
  target_link_libraries(platform_cuda PUBLIC tent_common)
  if(CUDAToolkit_FOUND)
    target_link_libraries(platform_cuda PUBLIC CUDA::cudart CUDA::cuda_driver)
  endif()
  if(USE_SUPA)
    target_link_libraries(platform_cuda PUBLIC ${SUPA_LIBRARIES})
  endif()
endif()
