name: 'Build Wheel (CUDA 13)'

on:
  workflow_call: {}

jobs:
  build-wheel-cu13:
    uses: ./.github/workflows/_build-wheel.yaml
    with:
      runner: ubuntu-22.04
      container: pytorch/manylinux2_28-builder:cuda13.0
      python-versions: '["3.10", "3.12"]'
      cuda: container
      variant-flag: CU13_BUILD
      torch-cuda-arch-list: '8.0;9.0'
      ep-torch-versions: '2.11.0;2.12.0;2.12.1;2.13.0'
      build-nvlink-allocator: true
      cmake-args: >-
        -DBUILD_UNIT_TESTS=OFF -DUSE_HTTP=ON -DUSE_ETCD=ON -DUSE_CUDA=ON
        -DWITH_EP=ON -DSTORE_USE_ETCD=ON -DENABLE_SCCACHE=ON -DCMAKE_BUILD_TYPE=Release
      artifact-prefix: mooncake-wheel-cu130
      version-override: 0.0.0.dev0
