name: CodeQuality Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check-draft:
    # We run all other jobs on PRs only if they are not draft PR
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    runs-on: ubuntu-22.04
    steps:
      - name: Preliminary checks on CI
        run: echo "Event name is ${{ github.event_name }}"

  format-check:
    name: Format Check
    runs-on: ubuntu-22.04
    needs: check-draft

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install formatting tools
        shell: bash
        run: |
          sudo apt-get update -y -qq
          sudo pip3 install 'clang_format==11.0.1' 'black>=24' cmake-format

      - name: List Installed Packages
        shell: bash
        run: pip3 freeze

      - name: Verify clang-format version
        shell: bash
        run: |
          clang-format --version
          clang-format --dump-config

      - name: Verify black version
        shell: bash
        run: black --version

      - name: Format Check
        shell: bash
        run: |
          make format-check

      - name: Show formatting differences (if any)
        if: failure()
        shell: bash
        run: |
          echo "Formatting check failed. Here are the differences:"
          python3 scripts/format.py --all --check || true