name: Release CUDA 13

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    if: ${{ !contains(github.ref_name, '-') }}
    uses: ./.github/workflows/_build-wheel.yaml
    with:
      runner: ubuntu-22.04
      container: pytorch/manylinux2_28-builder:cuda13.0
      cuda: container
      build-with-ep: '1'
      variant-flag: CU13_BUILD
      torch-cuda-arch-list: '8.0;9.0'
      ep-torch-versions: '2.11.0;2.12.0;2.12.1'
      build-nvlink-allocator: true
      cmake-args: >-
        -DBUILD_UNIT_TESTS=OFF -DUSE_HTTP=ON -DUSE_ETCD=ON -DUSE_CUDA=ON
        -DWITH_EP=ON -DSTORE_USE_ETCD=ON -DENABLE_SCCACHE=ON -DCMAKE_BUILD_TYPE=Release
      artifact-prefix: mooncake-wheel-cuda13

  build-arm64:
    if: ${{ !contains(github.ref_name, '-') }}
    uses: ./.github/workflows/_build-wheel.yaml
    with:
      runner: ubuntu-22.04-arm
      cuda: sbsa-13.0
      cmake-generator: Ninja
      variant-flag: CU13_BUILD
      torch-cuda-arch-list: '9.0'
      cmake-args: >-
        -DUSE_HTTP=ON -DUSE_CUDA=ON -DUSE_MNNVL=ON -DWITH_EP=OFF
        -DWITH_STORE_RUST=OFF -DENABLE_SCCACHE=ON -DCMAKE_BUILD_TYPE=Release
      artifact-prefix: mooncake-wheel-cuda13-arm64

  publish-release:
    if: ${{ !contains(github.ref_name, '-') }}
    needs: [build, build-arm64]
    uses: ./.github/workflows/_publish-wheel.yaml
    with:
      artifact-pattern: 'mooncake-wheel-cuda13*'
    secrets:
      pypi-token: ${{ secrets.PYPI_CU13_API_TOKEN }}
